### ISSUE TITLE
beerCatalogue.js

### ISSUE THREAD

**Issue by mirandalyng** [mybergquistrajic/beertastic#57]

**Comment by mybergquistrajic** [comment]
May need to create a PHP file for simply reading users, to be able to render a specific users hearts. Probably a quick fix, similar to readbeers.

**Comment by mybergquistrajic** [comment]
Update as of 12/12
PHP file added for users
Majority of file done, got to add/check:
- Fetch to change heart saves heart in database as string, not int... might be a problem on the PHP side?
- Add star-rating to the review  – Waiting for the rating.js file to be finished
- Link to beer when clicking on it – Waiting for the singleBeer.js file to be finished; to figure out linking etc
